### PR TITLE
Robot name flexibility

### PR DESCRIPTION
**Pull request by saxtot**
To allow the UI's development to continue without splitting into two versions, I added a field in the "config" to allow the user to enter the current robot's name.
To cover every scenario where 'markhor' was hard-coded, I use both useSelectors and a new selectRobotNameState to read the state, which now includes the robotName field.
The remaining uses of 'markhor' are from initialState arguments.
Some other minor changes include the removal of "dead code" and automatic import clean-ups.

### CODE REVIEW

**Review by GLDuval — COMMENTED** [review]
The code looks good to me! Thank you for showing some love to this repo :) Did you test this with a ros connection just to make sure it works?

**Comment by GLDuval** [comment]
@saxtot @amDeimos666 I just updated this branch to add the new semicolon rule

**Comment by saxtot** [comment]
> @saxtot @amDeimos666 I just updated this branch to add the new semicolon rule

**Comment by saxtot** [comment]
> The code looks good to me! Thank you for showing some love to this repo :) Did you test this with a ros connection just to make sure it works?

Yes, tested it on Markhor just now.

**Review by GLDuval — APPROVED** [review]

**Review by amDeimos666 — APPROVED** [review]

**Pull request merged**
