### PR TITLE
Tweak arm controls to improve usability

### PR DESCRIPTION
**Pull request by GLDuval**
After some testing, a latency was noticed when doing a long movement with the arm. To improve the performance of the controls the logic was changed a bit to make sure that arm commands are only published when the joystick is being moved. The deadman switch was also removed to improve the feeling of the controls. This change was requested and proven useful after testing Kinova's Gen3 robotic arm, since they use the same controls, but without a deadman switch.

### CODE REVIEW

**Review by saxtot — DISMISSED** [review]
Smart! Good catch there.

**Review by Leo-Dan — DISMISSED** [review]
Good job chef

**Comment by benmalenfant** [comment]
Nice! :) might be worth re-implementing the deadzone function in the future to get a more linear response, right now, it's just blocking the value until it reaches a threshold, then it jumps to the current value, this doesn't allow for fine control and might cause the arm to feel jumpy.  See attached graphs for explanaition

Current implementation : 
Dead-zone-nonlinearity-of-DC-motor

Desired implementation : 
download

**Comment by GLDuval** [comment]
> Nice! :) might be worth re-implementing the deadzone function in the future to get a more linear response, right now, it's just blocking the value until it reaches a threshold, then it jumps to the current value, this doesn't allow for fine control and might cause the arm to feel jumpy.  See attached graphs for explanaition
> 
> 
> 
> Current implementation : 
> 
> Dead-zone-nonlinearity-of-DC-motor
> 
> 
> 
> Desired implementation : 
> 
> download
> 
> 

I agree, I think it's simple enough to do it in this PR, we just need to normalize the values between 0 and 1. Right now the arm controls are smooth and it's not as jumpy as it would seem, but any new improvement is welcome!

**Comment by benmalenfant** [comment]
> > Nice! :) might be worth re-implementing the deadzone function in the future to get a more linear response, right now, it's just blocking the value until it reaches a threshold, then it jumps to the current value, this doesn't allow for fine control and might cause the arm to feel jumpy.  See attached graphs for explanaition
> > Current implementation :
> > Dead-zone-nonlinearity-of-DC-motor
> > Desired implementation :
> > download
> 
> I agree, I think it's simple enough to do it in this PR, we just need to normalize the values between 0 and 1. Right now the arm controls are smooth and it's not as jumpy as it would seem, but any new improvement is welcome!

fun link about deadzones : https://github.com/Minimuino/thumbstick-deadzones

**Comment by GLDuval** [comment]
@benmalenfant I added a simple fix that I think might work, I'll test it thoroughly tomorrow.

**Comment by benmalenfant** [comment]
Love it! Clean and simple

**Comment by GLDuval** [comment]
Just tested it and it works well! Gamepad axis values now scale between -1 and 1 linearly. This is ready to be merged

**Review by saxtot — APPROVED** [review]

**Review by benmalenfant — APPROVED** [review]

**Pull request merged**
