### PR TITLE
Fixed graph topic state on input change

### PR DESCRIPTION
**Pull request by GLDuval**
Fix an issue where the state would mutate between dispatches

### CODE REVIEW

**Comment by IceSentry** [comment]
Thanks for the PR, but you need to make sure you run the linter and formatter before creating a PR. You can run `npm run lint` to see the error in your console, but I would recommend to simply use vscode with the eslint extension to see the error directly in your editor. You can also run `npm run fix` to let eslint and prettier automatically fix the issues if possible, but I would also recommend to simply use the format on save option of vscode witht the eslint extension which will do essentially the same thing.

There's also some failing pipelines related to dependencies, I will fix that in a separate PR so you can ignore that.

**Comment by IceSentry** [comment]
Also, can you explain what was the issue that you noticed that led to this change?

**Comment by GLDuval** [comment]
You get the following error when you change the topic or message type inputs 
image

**Comment by GLDuval** [comment]
Yes! Thank you for reminding me to install eslint on my Linux environment, I'll write some beautiful code now :)

**Pull request merged**
